name: brain-annex-environment
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.22.4
  - pandas=1.4.3
  - pytest=6.2.5
  - jupyterlab=3.6.5
  - pip
  - pip:
      - neo4j==4.4.11
      - neoaccess==4.3.1