name: brain-annex-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas=1.5.3
  - pytest=6.2.5
  - jupyterlab=3.6.8
  - bcrypt=4.1.2
  - pip
  - pip:
      - neo4j==4.4.12
      - pymupdf==1.23.5